workflows:
  react_native_workflow:
    name: React Native Build and Test
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties" 
      
      - name: Install Expo CLI and eject
        script: | 
          npm install -g expo-cli
          expo eject
      - name: Set up app/build.gradle
        script: | 
          mv ./support-files/build.gradle android/app
           
      - name: Build Android
        script: |
          cd android && chmod +x gradlew && ./gradlew clean && ./gradlew assembleRelease
          ./gradlew bundleRelease
          cd .. && npx simpleapp bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

          npm run android
          cd android && ./gradlew assembleRelease
          npx simpleapp run-android --variant=release

      # - name: Build iOS
      #   script: |
      #     cd ios/
      #     pod install
      #     npx simpleapp run-ios --configuration=release

     
      - name: npm Starts
        script: |
          npm start
#          yarn start    

      # - name: Archive Build Artifacts
      #   script: |
      #     # Archive build artifacts, e.g., APK, IPA, or other necessary files

      # Additional steps for deployment or notifications can be added here
    artifacts:
      - build/**/*
      - ios/build/*.ipa
      - android/app/build/outputs/simpleapp.apk

    publishing:
      email:
        recipients:
          - manimv1268@gmail.com   